# frozen_string_literal: true

source 'https://rubygems.org'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

gem 'graphlient'
gem 'ons-firestore'

group :development do
  gem 'rubocop'
end
