# frozen_string_literal: true

source 'https://rubygems.org'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

gem 'google-cloud-firestore'
gem "google-protobuf", ">= 3.19.2"
gem 'graphql-client'

group :development do
  gem 'rubocop'
end
