# frozen_string_literal: true

source 'https://rubygems.org'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

gem 'google-cloud-firestore'
gem 'graphql-client'
gem 'ons-numbers'
gem 'pagy'
gem 'puma'
gem 'sinatra'

group :development do
  gem 'rubocop'
end
